MashreqPayroll/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
import notifications.urls

urlpatterns = [
                  path('i18n/', include('django.conf.urls.i18n')),
                  path('arkleab4superadmin/', admin.site.urls),
                  path('', include('home.urls'), name='home'),
                  path('currencies/', include('currencies.urls')),
                  path('com/', include('company.urls')),
                  path('emp/', include('employee.urls')),
                  path('defenition/', include('defenition.urls')),
                  path('manage/', include('manage_payroll.urls')),
                  path('payroll/', include('payroll_run.urls')),
                  path('element/', include('element_definition.urls')),
                  path('costing/', include('balanc_definition.urls')),
                  path('leave/', include('leave.urls')),
                  path('attendance/', include('attendance.urls')),
                  path('report/', include('report.urls')),
                  path('recruitment/', include('recruitment.urls')),
                  path('service/', include('service.urls')),
                  path('tasks/', include('task_management.urls')),
                  path('perf/', include('performance.urls')),
                  path('inbox/notifications/', include(notifications.urls, namespace='notifications')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += i18n_patterns (
#
# )

employee/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from employee import views
from urllib.parse import quote
from django.utils.encoding import iri_to_uri, uri_to_iri

app_name= 'employee'

urlpatterns =[
    path('employee/', include([
            ######################### Employee URLs ###################################
            path('new/', views.createEmployeeView, name='employee-create'),
            path('element/', views.copy_element_values, name='element-create'),
            path('information/listT/', views.listEmployeeView , name='list-employee'),
            path('information/listC/', views.listEmployeeCardView , name='list-employee-card'),
            path('correct/<int:pk>/', views.correctEmployeeView, name='correct-employee'),
             path('update/<int:pk>/', views.updateEmployeeView, name='update-employee'),
            path('view/<int:pk>/', views.viewEmployeeView, name='view-employee'),
            path('delete/<int:pk>/', views.deleteEmployeeView, name='delete-employee'),
            path('delete/forever/<int:pk>/', views.deleteEmployeePermanently, name='delete-employee-permanently'),

            path('link/employee/<int:pk>/structure/', views.create_link_employee_structure, name='link-structure-create'),
            path('update/link/employee/<int:pk>/structure/', views.update_link_employee_structure, name='link-structure-update'),
            path('ajax/', views.change_element_value, name='change-element-value'),
            path('employee/export/', views.export_employee_data, name='employee-export'),
            path('jobroll/new/<int:job_id>', views.createJobROll, name='new-jobroll'),
            path('leaves-history/' , views.list_employee_leave_requests , name='leaves-history'),
            path('element/new/<int:job_id>', views.create_employee_element, name='new-employee-element'),





    ])),

]

home/urls.py
from django.urls import path, include
from home import views
from django.contrib.auth import views as auth_views
from django.conf.urls.i18n import i18n_patterns

app_name = 'home'

urlpatterns=[
        path('en/', views.viewEN, name='en'),
        path('ar/', views.viewAR, name='ar'),
        path('login/', views.user_login, name='user-login'),
        path('logout/', views.user_logout, name='logout'),
        path('register/', views.register, name='register'),
        path('add-user/', views.addUserView, name='new-user'),
        path('', views.homepage, name='homepage'),
        # path('', views.pie_chart, name='pie-chart'),
        path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
          name='password_change_done'),

        path('password_change/', views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
          name='password_change'),

        path('password_reset/done/', views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
        name='password_reset_done'),

        path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
        path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

        path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
        name='password_reset_complete'),
        #groups
        path('groups/',include([
            path('',views.group_list,name='group_list'),
            path('<int:pk>/',views.group_view,name='group_view'),
            path('new/',views.create_groups,name='create_group'),
            path('update/<int:pk>',views.edit_groups,name='update_group'),
            path('assign/',views.assign_role,name='assign_user'),
            path('users/',views.user_group_list,name="user_groups"),
            path('<int:pk>/delete',views.user_group_delete, name='reset_user_group')

        ])),
]

performance/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from performance import views

# gehad : createPerformance urls.
app_name= 'performance'

urlpatterns =[
    path('performance/', include([
            ######################### Performance URLs ###################################
            path('create/', views.createPerformance, name='performance-create'),
            path('edit/<int:pk>/', views.updatePerformance, name='performance-edit'),
            path('delete/<int:pk>/', views.deletePerformance, name='performance-delete'),
            path('list/', views.listPerformance, name='performance-list'),
            path('performance/<int:pk>/', views.performanceView, name='performance'),
            #performanceRating
            path('create/rating/<int:per_id>/', views.createPerformanceRating, name='rating-create'),
            path('update/rating/<int:pk>/', views.updatePerformanceRating, name='rating-update'),
            #management
            path('management/<int:pk>/', views.performanceManagement, name='management'),
            #segments
            path('segments/<int:pk>/<int:ret_id>/', views.listSegment, name='segments'),
            path('create/segment/<int:per_id>/<int:ret_id>/', views.createSegment, name='segment-create'),
            path('edit/segment/<int:pk>/<int:ret_id>/', views.updateSegment, name='segment-edit'),
            path('delete/segment/<int:pk>/<int:ret_id>/', views.deleteSegment, name='segment-delete'),
            #employeeRate
            path('employees/', views.employees, name='employees'),
            path('performances/', views.employeePerformances), #ajax
            path('employee/<int:pk>/<int:emp_id>/', views.employee_rates, name='employee-rate'),
            path('employee/overview/<int:per_id>/<int:emp_id>/create/', views.create_employee_overview_rate, name='create-employee-overview'),
            path('employee/overview/<int:per_id>/<int:emp_id>/update/', views.update_employee_overview_rate, name='update-employee-overview'),
            path('employee/segment/questions/<int:pk>/<int:emp_id>/', views.employee_segment_questions, name='employee-segment-questions'),
            path('employee/segment/question/<int:pk>/<int:emp_id>/create/', views.create_employee_question_rate, name='create-employee-question-rate'),
            path('employee/segment/question/<int:pk>/<int:emp_id>/update/', views.update_employee_question_rate, name='update-employee-question-rate'),
            path('emp/performances/<int:pk>/', views.employee_performances, name='employee-performances'),
              ])),
]
        

employee/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from django.db.models import Q
from company.models import Department, Job, Grade, Position
from manage_payroll.models import Payroll_Master
from employee.models import Employee, JobRoll, Payment, Employee_Element, EmployeeStructureLink, Employee_File , Employee_Depandance
from defenition.models import LookupType, LookupDet
from element_definition.models import Element_Master, Element_Link, SalaryStructure
from django.shortcuts import get_object_or_404, get_list_or_404
from datetime import date
from django.forms import BaseInlineFormSet

common_items_to_execlude = (
    'enterprise',
    'created_by', 'creation_date',
    'last_update_by', 'last_update_date',
    'attribute1', 'attribute2', 'attribute3',
    'attribute4', 'attribute5', 'attribute6',
    'attribute7', 'attribute8', 'attribute9',
    'attribute10', 'attribute11', 'attribute12',
    'attribute13', 'attribute14', 'attribute15',
)


###############################################################################

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = '__all__'
        widgets = {
            'insured': forms.CheckboxInput(attrs={
                'style': 'padding: 25px; margin:25px;'
            }),
            'has_medical': forms.CheckboxInput(attrs={
                'style': 'padding: 25px; margin:25px;'
            }),
            'is_active': forms.CheckboxInput(attrs={
                'style': 'padding: 25px; margin:25px;'
            }),
        }
        exclude = common_items_to_execlude

    def __init__(self, *args, **kwargs):
        super(EmployeeForm, self).__init__(*args, **kwargs)
        self.fields['date_of_birth'].widget.input_type = 'date'
        self.fields['hiredate'].widget.input_type = 'date'
        self.fields['terminationdate'].widget.input_type = 'date'
        self.fields['emp_start_date'].widget.input_type = 'date'
        self.fields['emp_end_date'].widget.input_type = 'date'
        self.fields['insurance_date'].widget.input_type = 'date'
        self.fields['medical_date'].widget.input_type = 'date'
        for field in self.fields:
            if self.fields[field].widget.input_type == 'checkbox':
                self.fields[field].widget.attrs['class'] = ''
            else:
                self.fields[field].widget.attrs['class'] = 'form-control parsley-validated'
        self.helper = FormHelper()
        self.helper.form_show_labels = True


class JobRollForm(forms.ModelForm):
    class Meta:
        model = JobRoll
        fields = '__all__'
        exclude = common_items_to_execlude

    def __init__(self, user_v, *args, **kwargs):
        super(JobRollForm, self).__init__(*args, **kwargs)
        self.fields['start_date'].widget.input_type = 'date'
        self.fields['end_date'].widget.input_type = 'date'
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control parsley-validated'
        self.helper = FormHelper()
        self.helper.form_show_labels = True
        self.fields['contract_type'].queryset = LookupDet.objects.filter(
            lookup_type_fk__lookup_type_name='EMPLOYEE_TYPE',lookup_type_fk__enterprise=user_v.company)
        self.fields['position'].queryset = Position.objects.filter((Q(department__enterprise=user_v.company)), (
                Q(end_date__gte=date.today()) | Q(end_date__isnull=True)))
        self.fields['payroll'].queryset = Payroll_Master.objects.filter((Q(enterprise=user_v.company)), (
                Q(end_date__gte=date.today()) | Q(end_date__isnull=True)))
        self.fields['manager'].queryset = Employee.objects.filter(enterprise=user_v.company)


class PaymentForm(forms.ModelForm):
    class Meta:
        model = Payment
        fields = "__all__"
        exclude = common_items_to_execlude

    def __init__(self, *args, **kwargs):
        super(PaymentForm, self).__init__(*args, **kwargs)
        self.fields['start_date'].widget.input_type = 'date'
        self.fields['end_date'].widget.input_type = 'date'
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control parsley-validated'
        self.helper = FormHelper()
        self.helper.form_show_labels = True


# class PaymentTotalCheckFormSet(BaseInlineFormSet):
#     def clean(self):
#         super().clean()
#         total_percentage = sum(f.cleaned_data['percentage'] for f in self.forms)
#         if total_percentage != 100:
#             raise forms.ValidationError("Total percentage must be 100")

Employee_Payment_formset = forms.inlineformset_factory(Employee, Payment, form=PaymentForm, can_delete=False)


class EmployeeElementForm(forms.ModelForm):
    class Meta:
        model = Employee_Element
        fields = "__all__"
        exclude = ('emp_id',) + common_items_to_execlude

    def __init__(self, *args, **kwargs):
        super(EmployeeElementForm, self).__init__(*args, **kwargs)
        self.fields['start_date'].widget.input_type = 'date'
        self.fields['end_date'].widget.input_type = 'date'
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control parsley-validated'
        self.helper = FormHelper()
        self.helper.form_show_labels = True


Employee_Element_Inline = forms.inlineformset_factory(Employee, Employee_Element, form=EmployeeElementForm,
                                                      can_delete=False, extra=8)


class EmployeeStructureLinkForm(forms.ModelForm):
    class Meta:
        model = EmployeeStructureLink
        fields = "__all__"
        exclude = common_items_to_execlude + ('employee',)

    def __init__(self, *args, **kwargs):
        super(EmployeeStructureLinkForm, self).__init__(*args, **kwargs)
        self.fields['start_date'].widget.input_type = 'date'
        self.fields['end_date'].widget.input_type = 'date'
        self.fields['salary_structure'].queryset = SalaryStructure.objects.filter(
            Q(end_date__isnull=True) | Q(end_date__gt=date.today()))

        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control parsley-validated'
        self.helper = FormHelper()
        self.helper.form_show_labels = True

class EmployeeFileForm(forms.ModelForm):
    class Meta:
        model = Employee_File
        fields = "__all__"
        exclude = common_items_to_execlude

    def __init__(self , *args, **kwargs):
        super(EmployeeFileForm , self).__init__(*args , **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control parsley-validated'
        self.helper = FormHelper()
        self.helper.form_show_labels = True

Employee_Files_inline = forms.inlineformset_factory(Employee, Employee_File, form=EmployeeFileForm, extra=0)


class EmployeeDepandanceForm(forms.ModelForm):
    class Meta:
        model = Employee_Depandance
        fields = "__all__"
        exclude = ('emp_id', 'last_updated_at' ,'created_by','last_updated_by')
    def __init__(self , *args, **kwargs):
        super(EmployeeDepandanceForm , self).__init__(*args , **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control parsley-validated'
        self.helper = FormHelper()
        self.helper.form_show_labels = True

Employee_depandance_inline = forms.inlineformset_factory(Employee, Employee_Depandance, form=EmployeeDepandanceForm, extra=0)

performance/templates/create-performance.html
{% extends 'master.html'%}
{% load staticfiles%}
{% load l10n %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block body%}
<style>

</style>
  <div class="container-fluid">
    <form method="POST" id="myform" enctype="multipart/form-data">
      {% csrf_token %}
    <div class="row">
      <div class="col-md-8">
        <h4 class="c-grey-900">{{page_title|title}}</h4>
      </div>
      <div class="col-md-15">
        <div class="gap-10 peers {% if LANGUAGE_BIDI %} push-left {% else %} push-right {% endif %}">
          <div class="peer"><button type="submit" onclick="change_x()" id="button" class="btn cur-p btn-primary"  name ='Save and exit'>{% trans "Save" %}</button></div>
          <div class="peer"><a href="{% url 'performance:performance-list' %}"  onclick="change_x()" class="btn cur-p btn-secondary">{% trans "Back to List" %}</a></div>
        </div>
      </div>
    </div>

    <div class="mt-1">
      <div class="bgc-white p-20 bd">
        <h6 class="c-grey-900">{% trans "Performance " %}</h6>
        <div class="mT-30">
          <div class="form-row">
            <div class="form-group col-md-3">
              <label for="inputCity">{% trans "Performance Name" %}</label>
              {{ performance_form.performance_name}}
            </div>
            <div class="form-group col-md-3">
              <label for="inputCity">{% trans "Company" %}</label>
              <br>
              <p  class="form-control" id="formGroupExampleInput">{{ company }}</p>
            </div>

            <div class="form-group col-md-3">
              <label class="fw-500">{% trans "Start Date" %}</label>
              <div class="timepicker-input input-icon form-group">
                <div class="input-group">
                  <div class="input-group-addon bgc-white bd bdwR-0">
                    <i class="ti-calendar"></i></div>
                  {{ performance_form.start_date}}
                </div>
              </div>
            </div>
            <div class="form-group col-md-3">
              <label class="fw-500">{% trans "End Date" %}</label>
              <div class="timepicker-input input-icon form-group">
                <div class="input-group">
                  <div class="input-group-addon bgc-white bd bdwR-0">
                    <i class="ti-calendar"></i></div>
                  {{ performance_form.end_date}}
                </div>
              </div>
            </div>

            <div class="form-row">
            <div class="form-group col-md-4">
              <label for="inputPassword4">{% trans "Department" %}</label>
              {{ performance_form.department}}
            </div>
            <div class="form-group col-md-4">
              <label for="inputCity">{% trans "Job" %}</label>
              {{ performance_form.job}}
            </div>

            <div class="form-group col-md-4">
              <label for="inputCity">{% trans "Position" %}</label>
              {{ performance_form.position}}
            </div>
            </div>
          </div>
            <br>
            <div class="form-row" style="text-align: right;">
              <div class="form-group col-md-12">
              <div class="peer"><button type="submit" onclick="change_x()" id="button" class="btn cur-p btn-primary" name ='Save and add' >{% trans "Next" %}</button></div>
            </div>
            </div>

  </form>
</div>


{% endblock body%}

performance/templates/employee-rate.html
{% extends 'master.html'%}
{% load staticfiles%}
{% load l10n %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block body%} 



  <div class="container-fluid">
    <div class="row">
      <div class="col-md-8">
        <h4 class="c-grey-900">
        <span  style="color: #ed9943;">{{employee.emp_name}}</span> Rate for 
        <span  style="color: #ed9943;">{{ performance.performance_name }}</span> performance 
        </h4>
      </div>
      <div class="col-md-15">
        <div class="gap-10 peers {% if LANGUAGE_BIDI %} push-left {% else %} push-right {% endif %}">
          <div class="peer"><a href="{% url 'performance:employees' %}" onclick="change_x()" class="btn cur-p btn-secondary">{% trans "Back to List" %}</a></div>
        </div>
      </div>
    </div>
    <br>
 
    <h4 style="text-align: center;">{{ comleted_segments }} Completed Segments of {{  segments.all.count }} Segments</h4> 
    <section class="panel panel-default">
      <header class="panel-heading bg-light">
        <ul class="nav nav-tabs nav-justified ">
          <li id="overview"   style="width: 20%;"><a href="{% url 'performance:create-employee-overview' per_id=performance.id emp_id=employee.id %}" aria-selected="true">{% trans "Over View" %}</a></li>
          {% if segments.count == 1 %}
          {% for segment in segments %}
          <li id="active{{segment.id}}" style="width: 80%;"><a href="{% url 'performance:employee-segment-questions' pk=segment.id emp_id=employee.id %}"  aria-selected="false">{{segment}}</a></li>
          {% endfor %}
          {% elif segments.count == 2  %}
          {% for segment in segments %}
          <li id="active{{segment.id}}"  style="width: 40%;"><a href="{% url 'performance:employee-segment-questions' pk=segment.id emp_id=employee.id %}"   aria-selected="false">{{segment}}</a></li>
          {% endfor %}
          {% elif segments.count == 3  %}
          {% for segment in segments %}
          <li id="active{{segment.id}}"  style="width: 26%;"><a href="{% url 'performance:employee-segment-questions' pk=segment.id emp_id=employee.id %}"   aria-selected="false">{{segment}}</a></li>
          {% endfor %}
          {% elif segments.count == 4  %}
          {% for segment in segments %}
          <li id="active{{segment.id}}" style="width: 20%;"><a href="{% url 'performance:employee-segment-questions' pk=segment.id emp_id=employee.id %}"   aria-selected="false">{{segment}}</a></li>
          {% endfor %}
          {% elif segments.count == 5  %}
          {% for segment in segments %}
          <li id="active{{segment.id}}"  style="width: 16%;"><a href="{% url 'performance:employee-segment-questions' pk=segment.id emp_id=employee.id %}"   aria-selected="false">{{segment}}</a></li>
          {% endfor %}
          {% else  %}
          {% for segment in segments %}
          <li id="active{{segment.id}}"  style="width: 10%;"><a href="{% url 'performance:employee-segment-questions' pk=segment.id emp_id=employee.id %}"   aria-selected="false">{{segment}}</a></li>
          {% endfor %}
          {% endif %}
        </ul>
      </header>
  <!-- rate -->
  {% block rate %}
  {% endblock rate %}
</section>
    </div>

{% endblock body%}

performance/templates/performance-list.html
{% extends 'master.html'%}
{% load staticfiles%}
{% load crispy_forms_tags %}
{% load l10n %}
{% load i18n %}
{% block body%}


  <div class="row" style="margin-left:0px;">
    <div class="col-md-8">
      <h4 class="c-grey-900">{{page_title|title}}</h4>
    </div>
    <div class="col-md-4">
      <div class="gap-10 peers {% if LANGUAGE_BIDI %} push-left {% else %} push-right {% endif %}">
        <div class="peer"><a href="{% url 'performance:performance-create' %}" class="btn cur-p btn-primary">{% trans "Add Performance" %}</a></div>

      </div>
    </div>
  </div>
  <div class="row" style="margin-left:0px;">
    <div class="col-md-12">
      <div class="bgc-white bd bdrs-3 p-20 mB-20">
        <table class="table table-striped table-bordered" cellspacing="0" id="dataTable" width="100%">
          <thead>
            <tr>
              <th>#</th>
              <th>{% trans "Performance Name" %}</th>
              <th>{% trans "Company" %}</th>
              <th>{% trans "Department" %}</th>
              <th>{% trans "Job" %}</th>
              <th>{% trans " Position" %}</th>
              <th>{% trans "Start Date" %}</th>
              <th>{% trans "End Date" %}</th>
              <th>{% trans "Actions" %}</th>
            </tr>
          </thead>
          <tbody>
            {% for performance in performances_list %}
            <tr>
              <td scope="row">{{ forloop.counter }}</td>
              <td>
                 <a href="{% url 'performance:performance' pk=performance.id%}">
                {{ performance.performance_name }}</a>
              </td>
              <td>{{ performance.company }}</td>
              <td>{{ performance.department }}</td>
              <td>{{ performance.position }}</td>
              <td>{{ performance.job }}</td>
              <td>{{ performance.start_date }}</td>
              <td>{{ performance.end_date }}</td>
              <td class="Actions">
                <div class="w-100 gap-10 peers">
                  <div class="peer">
                    <a href="{% url 'performance:management' pk=performance.pk %}">
                      <button type="button" class="btn cur-p btn-outline-primary">
                        <i class="fas fa-search-plus"></i>
                      </button>
                    </a>
                  </div>
                  <div class="peer">
                    <a href="{% url 'performance:performance-edit' pk=performance.pk %}">
                      <button type="button" class="btn cur-p btn-outline-success">
                        <i class="fas fa-user-edit"></i>
                      </button>
                    </a>
                  </div>
                  <div class="peer">
                    <a href="#">
                      <button type="button" class="btn cur-p btn-outline-danger" data-toggle="modal" data-target="#delete-modal{{performance.pk}}">
                        <i class="fa fa-trash"></i>
                      </button>
                    </a>
                  </div>
                </div>
              </td>
            </tr>
            <!-- Delete Modal -->
            <div class="modal fade" id="delete-modal{{performance.pk}}" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-body">
                    <p>{% trans "Are you sure you want to delete " %} {{ performance.performance_name }} ?</p>
                    <button class="btn btn-secondary" data-dismiss="modal">{% trans "No" %}</button>
                    <a href="{% url 'performance:performance-delete' pk=performance.pk %}"  class="btn btn-danger" type="button">{% trans "Delete" %}</a>
                  </div>
                </div>
              </div>
            </div>

            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>


{% endblock body%}

performance/templates/performance-management.html
{% extends 'master.html'%}
{% load staticfiles%}
{% load l10n %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block body%}
<style>

</style>
  <div class="container-fluid">
        <h4 class="c-grey-900">{{page_title|title}}</h4>

        <div class="form-row col-md-12 p-20">
          {% if overall_rating.count != 0 %}
        <div class="col-sm-4">
          <div class="card">
            <div class="card-header">
              {% trans "Segments"%}
            </div>
            <div class="card-body">
              <h5 class="card-title">   
                {% trans "Overall"%}
              </h5>
              <p class="card-text">{% trans "All Overall Segments"%}</p>
              <a href="{% url 'performance:segments' pk=pk ret_id=1 %}"  class="btn btn-primary">Segments</a>
            </div>
          </div>
        </div>
        {% endif %}

    {% if core_rating.count != 0 %}
    <div class="col-sm-4">
      <div class="card">
        <div class="card-header">
          {% trans "Segments"%}
        </div>
        <div class="card-body">
          <h5 class="card-title">
            {% trans "Core"%}
          </h5>
          <p class="card-text">{% trans "All Core Segments"%}</p>
          <a href="{% url 'performance:segments' pk=pk ret_id=2 %}"  class="btn btn-primary">Segments</a>
        </div>
      </div>
    </div>
    {% endif %}

  {% if job_rating.count != 0 %}
  <div class="col-sm-4">
      <div class="card">
        <div class="card-header">
          {% trans "Segments"%}
        </div>
        <div class="card-body">
          <h5 class="card-title">
            {% trans "Job Role"%}
          </h5>
          <p class="card-text">{% trans "All Job Role Segments"%}</p>
          <a href="{% url 'performance:segments' pk=pk ret_id=3 %}"  class="btn btn-primary">Segments</a>
        </div>
      </div>
  </div>
  {% endif %}

     
{% endblock body%}

performance/templates/segment-list.html
{% extends 'master.html'%}
{% load staticfiles%}
{% load crispy_forms_tags %}
{% load l10n %}
{% load i18n %}
{% block body%}


  <div class="row" style="margin-left:0px;">
    <div class="col-md-8">
      <h4 class="c-grey-900">{{page_title|title}}</h4>
    </div>
  </div>

  <div class="row" style="margin-right:0px;" >
    <div class="col-md-12">
      <div class="gap-10 peers {% if LANGUAGE_BIDI %} push-left {% else %} push-right {% endif %}">
        <div class="peer"><a href="{% url 'performance:management' pk=pk%}" class="btn cur-p btn-primary">{% trans "Back to List" %}</a></div>
        <div class="peer"><a href="{% url 'performance:segment-create' per_id=pk  ret_id=ret_id %}" class="btn cur-p btn-primary">{% trans "Add Segment" %}</a></div>
      </div>
    </div>
  </div>
  <br>

  <div class="row" style="margin-left:0px;">
    <div class="col-md-12">
      <div class="bgc-white bd bdrs-3 p-20 mB-20">
        <table class="table table-striped table-bordered" cellspacing="0" id="dataTable" width="100%">
          <thead>
            <tr>
              <th>#</th>
              <th>{% trans "Title" %}</th>
              <th>{% trans "Description" %}</th>
              <th>{% trans "Questions" %}</th>
              <th>{% trans "Actions" %}</th>

            </tr>
          </thead>
          <tbody>
            {% for segment in segments %}
            <tr>
              <td scope="row">{{ forloop.counter }}</td>
              <td>{{ segment.title }}</td>
              <td>{{ segment.desc }}</td>
              <td>{{ segment.questions.all.count }}</td>

              <td class="Actions">
                <div class="w-100 gap-10 peers">
                  <div class="peer">
                    <a href="{% url 'performance:segment-edit' pk=segment.id  ret_id=ret_id %}">
                      <button type="button" class="btn cur-p btn-outline-success">
                        <i class="fas fa-user-edit"></i>
                      </button>
                    </a>
                  </div>
                  <div class="peer">
                    <a href="#">
                      <button type="button" class="btn cur-p btn-outline-danger" data-toggle="modal" data-target="#delete-modal{{segment.pk}}">
                        <i class="fa fa-trash"></i>
                      </button>
                    </a>
                  </div>
                </div>
              </td>
            </tr>
            <!-- Delete Modal -->
            <div class="modal fade" id="delete-modal{{segment.pk}}" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-body">
                    <p>{% trans "Are you sure you want to delete " %} {{ segment.title }} ?</p>
                    <button class="btn btn-secondary" data-dismiss="modal">{% trans "No" %}</button>
                    <a href="{% url 'performance:segment-delete' pk=segment.id  ret_id=ret_id %}" class="btn btn-warning" type="button">{% trans "Delete" %}</a>
                  </div>
                </div>
              </div>
            </div>

            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>


{% endblock body%}