MashreqPayroll/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
import notifications.urls

urlpatterns = [
                  path('i18n/', include('django.conf.urls.i18n')),
                  path('arkleab4superadmin/', admin.site.urls),
                  path('', include('home.urls'), name='home'),
                  path('currencies/', include('currencies.urls')),
                  path('com/', include('company.urls')),
                  path('emp/', include('employee.urls')),
                  path('defenition/', include('defenition.urls')),
                  path('manage/', include('manage_payroll.urls')),
                  path('payroll/', include('payroll_run.urls')),
                  path('element/', include('element_definition.urls')),
                  path('costing/', include('balanc_definition.urls')),
                  path('leave/', include('leave.urls')),
                  path('attendance/', include('attendance.urls')),
                  path('report/', include('report.urls')),
                  path('recruitment/', include('recruitment.urls')),
                  path('service/', include('service.urls')),
                  path('tasks/', include('task_management.urls')),
                  path('perf/', include('performance.urls')),
                  path('inbox/notifications/', include(notifications.urls, namespace='notifications')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += i18n_patterns (
#
# )

employee/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from employee import views
from urllib.parse import quote
from django.utils.encoding import iri_to_uri, uri_to_iri

app_name= 'employee'

urlpatterns =[
    path('employee/', include([
            ######################### Employee URLs ###################################
            path('new/', views.createEmployeeView, name='employee-create'),
            path('element/', views.copy_element_values, name='element-create'),
            path('information/listT/', views.listEmployeeView , name='list-employee'),
            path('information/listC/', views.listEmployeeCardView , name='list-employee-card'),
            path('correct/<int:pk>/', views.correctEmployeeView, name='correct-employee'),
             path('update/<int:pk>/', views.updateEmployeeView, name='update-employee'),
            path('view/<int:pk>/', views.viewEmployeeView, name='view-employee'),
            path('delete/<int:pk>/', views.deleteEmployeeView, name='delete-employee'),
            path('delete/forever/<int:pk>/', views.deleteEmployeePermanently, name='delete-employee-permanently'),

            path('link/employee/<int:pk>/structure/', views.create_link_employee_structure, name='link-structure-create'),
            path('update/link/employee/<int:pk>/structure/', views.update_link_employee_structure, name='link-structure-update'),
            path('ajax/', views.change_element_value, name='change-element-value'),
            path('employee/export/', views.export_employee_data, name='employee-export'),
            path('jobroll/new/<int:job_id>', views.createJobROll, name='new-jobroll'),
            path('leaves-history/' , views.list_employee_leave_requests , name='leaves-history'),
            path('element/new/<int:job_id>', views.create_employee_element, name='new-employee-element'),





    ])),

]

home/urls.py
from django.urls import path, include
from home import views
from django.contrib.auth import views as auth_views
from django.conf.urls.i18n import i18n_patterns

app_name = 'home'

urlpatterns=[
        path('en/', views.viewEN, name='en'),
        path('ar/', views.viewAR, name='ar'),
        path('login/', views.user_login, name='user-login'),
        path('logout/', views.user_logout, name='logout'),
        path('register/', views.register, name='register'),
        path('add-user/', views.addUserView, name='new-user'),
        path('', views.homepage, name='homepage'),
        # path('', views.pie_chart, name='pie-chart'),
        path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
          name='password_change_done'),

        path('password_change/', views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
          name='password_change'),

        path('password_reset/done/', views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
        name='password_reset_done'),

        path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
        path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

        path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
        name='password_reset_complete'),
        #groups
        path('groups/',include([
            path('',views.group_list,name='group_list'),
            path('<int:pk>/',views.group_view,name='group_view'),
            path('new/',views.create_groups,name='create_group'),
            path('update/<int:pk>',views.edit_groups,name='update_group'),
            path('assign/',views.assign_role,name='assign_user'),
            path('users/',views.user_group_list,name="user_groups"),
            path('<int:pk>/delete',views.user_group_delete, name='reset_user_group')

        ])),
]

leave/urls.py
from django.urls import path
from leave import views

app_name = 'leave'

urlpatterns = [
    path('list_leave/', views.list_leave, name='list_leave'),
    path('del_leave/<int:id>', views.delete_leave_view, name='del_leave'),
    path('add_leave/', views.add_leave, name='add_leave'),
    path('edit_leave/<int:id>', views.edit_leave, name='edit_leave'),
    path('add_leave_master/', views.add_leave_master, name='add_leave_master'),
    path('list-leave-master/', views.list_leave_master, name='list-leave-master'),
    path('edit_leave_master/<int:id>', views.edit_leave_master, name='edit_leave_master'),
    path('del_leave_master/<int:id>', views.del_leave_master, name='del_leave_master'),
    path('leave-approve/<int:leave_id>/<str:redirect_to>/', views.leave_approve, name='leave-approve'),
    path('leave-unapprove/<int:leave_id>/<str:redirect_to>/', views.leave_unapprove, name='leave-unapprove'),
    path('leave-balance/', views.Elmplyees_Leave_Balance.as_view(), name='leave-balance'),

    path('leave-balance/edit/<int:leave_balance_id>/', views.edit_employee_leaves_balance, name='leave_balance_edit'),
    path('leave-balance/delete/<int:leave_balance_id>/', views.delete_leave_balance, name='leave_balance_delete'),

    path('leave-balance-add/', views.create_employee_leave_balance, name='leave-balance-create'),
    path('leave-balance-list/<int:employee_id>/', views.view_employee_leaves_list, name='employee-leave-list'),
    path('leave-type/', views.get_leave_type, name='leave_type'),

]

service/urls.py
from django.urls import path
from service import views

# TEMPLATE TAGGING
app_name = 'service'
urlpatterns = [
    path('bussiness/travel/list/', views.services_list, name='services_list'),
    path('bussiness/travel/delete/<int:id>', views.services_delete, name='services_delete'),
    path('bussiness/travel/edit/<int:id>', views.services_edit, name='services_edit'),
    path('bussiness/travel/update/<int:id>/', views.services_update, name='services-update'),
    path('services/create/', views.services_create, name='services_create'),
    path('service/approve/<int:service_id>/<str:redirect_to>', views.service_approve, name='service-approve'),
    path('service/unapprove/<int:service_id>/<str:redirect_to>', views.service_unapprove, name='service-unapprove'),

    path('purchase/list/', views.purchase_request_list, name='purchase-request-list'),
    path('purchase/order/create/', views.purchase_request_create, name='purchase-request-create'),
    path('purchase/order/update/<int:id>/', views.purchase_request_update, name='purchase-request-update'),
    path('purchase/approve/<int:order_id>', views.purchase_request_approve, name='purchase-approve'),
    path('purchase/unapprove/<int:order_id>', views.purchase_request_unapprove, name='purchase-unapprove'),
]

home/models.py
from django.db import models

# Create your models here.

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from custom_user.models import User
from django.utils.translation import ugettext_lazy as _
from django.db.models import Q
from django.contrib.auth.models import Group, Permission
from django.contrib.admin.widgets import FilteredSelectMultiple


class CustomUserCreationForm(UserCreationForm):
    company_name = forms.CharField(
        max_length=60, required=True, help_text='This Field is Required.', label=_('Name'))
    business_unit_name = forms.CharField(
        max_length=40, required=True, label=_('Business Unit Name'))
    reg_tax_num = forms.CharField(
        max_length=40, required=True, label=_('Reg Tax Num'))
    commercail_record = forms.CharField(
        max_length=40, required=True, label=_('Commercail Record '))

    class Meta(UserCreationForm):
        model = User
        fields = ('company_name', 'business_unit_name',
                  'reg_tax_num', 'commercail_record', 'username', 'email')

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control parsley-validated'


class AddUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'employee_type', 'email')

    def __init__(self, *args, **kwargs):
        super(AddUserForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control parsley-validated'


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'employee_type', 'email')

# group forms


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = '__all__'
        widgets = {
            'permissions': FilteredSelectMultiple("Permission", False, attrs={'rows': '3'}),
        }

        def __init__(self, *args, **kwargs):
            super(EmployeeStructureLinkForm, self).__init__(*args, **kwargs)
            for field in self.fields:
                self.fields[field].widget.attrs['class'] = 'form-control parsley-validated'
            self.helper = FormHelper()
            self.helper.form_show_labels = True


class GroupViewForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = '__all__'
        widgets = {
            'permissions': FilteredSelectMultiple("Permission", False, attrs={'rows': '3', 'disabled': True}),
            'name': forms.TextInput(attrs={'readonly': 'readonly'}),
            # 'permissions':forms.TextInput(attrs={'readonly':'readonly'})
        }


class GroupAdminForm(forms.ModelForm):
    group = forms.ModelChoiceField(queryset=Group.objects.all(),
                                   required=True)
    user = forms.ModelChoiceField(
        queryset=User.objects.all(),
        required=True
    )

    class Meta:
        model = User
        fields = ['user', 'group']

home/templates/add-user.html
{% extends 'master.html' %}
{% load staticfiles%}
{% load i18n %}
{% load l10n %}

{% block body %}
<!--  -->
<div class="container-fluid">
  <div class="mt-1">
    <div class="bgc-white p-20 bd">
      <div class="row">
        <div class="col-md-8">
          <h1 class="c-grey-900" style="text-align:center;">
            <strong>{{page_title|title}}</strong>
          </h1>
        </div>
      </div>
      <h5 class="c-grey-900">Fill out the form</h5>
      <div class="mT-30">
        <form method="POST">
          {% csrf_token %}
          <div class="form-group row">
            <label class="col-sm-2 col-form-label">{{add_user.username.label}}</label>
            <div class="col-sm-4">
              {{add_user.username}}
            </div>
          </div>
          <div class="form-group row">
            <label class="col-sm-2 col-form-label">{{add_user.employee_type.label}}</label>
            <div class="col-sm-4">
              {{add_user.employee_type}}
            </div>
          </div>

          <div class="form-group row"">
              <label class=" col-sm-2 col-form-label">{{add_user.email.label}}</label>
            <div class="col-sm-4">
              {{add_user.email}}
            </div>
          </div>
          <div class="form-group row">
            <label class="col-sm-2 col-form-label">{{add_user.password1.label}}</label>
            <div class="col-sm-4">
              {{add_user.password1}}
            </div>
          </div>
          <div class="form-group row">
            <label class="col-sm-2 col-form-label">{{add_user.password2.label}}</label>
            <div class="col-sm-4">
              {{add_user.password2}}
            </div>
          </div>

          <div class="form-group row">
            <div class="col-sm-10">
              <button type="submit" class="btn btn-primary">Submit</button>
              <button type="button" class="btn btn-default">
                <a href="{% url 'home:homepage' %}">Cancel</a>
              </button>
            </div>

          </div>
        </form>

      </div>
    </div>
  </div>
</div>
<script>
  window.addEventListener("beforeunload", function (e) {
    var confirmationMessage = 'It looks like you have been editing something. '
                            + 'If you leave before saving, your changes will be lost.';

    (e || window.event).returnValue = confirmationMessage; //Gecko + IE
    return confirmationMessage; //Gecko + Webkit, Safari, Chrome etc.
});
</script>
{% endblock body %}

home/templates/groups_list.html
{% extends 'master.html'%}
{% load staticfiles%}
{% load crispy_forms_tags %}
{% load l10n %}
{% load i18n %}
{% block body%}


  <div class="row" style="margin-left:0px;">
    <div class="col-md-8">
      <h4 class="c-grey-900">{{page_title|title}}</h4>
    </div>
    <div class="col-md-4">
      <div class="gap-10 peers {% if LANGUAGE_BIDI %} push-left {% else %} push-right {% endif %}">
        <div class="peer"><a href="{% url 'home:create_group' %}" class="btn cur-p btn-primary">{% trans "Add" %}</a></div>
        <!-- <div class="peer"><a href="{% url 'employee:list-employee-card' %}" class="btn cur-p btn-secondary">{% trans "Card View" %}</a></div> -->
      </div>
    </div>
  </div>
  <div class="row" style="margin-left:0px;">
    <div class="col-md-12">
      <div class="bgc-white bd bdrs-3 p-20 mB-20">
        <table class="table table-striped table-bordered" cellspacing="0" id="dataTable" width="100%">
          <thead>
            <tr>
              <th>#</th>
              <th>group Name</th>
              <th width="30%">{% trans "Actions" %}</th>
            </tr>
          </thead>
          <tbody>
            {% for group in groups %}
            <tr>
              <td scope="row">{{ forloop.counter }}</td>
              <td>{{ group.name }}</td>
              <td class="Actions">
                <div class="w-100 gap-10 peers">
                  <div class="peer">
                    <a href="{% url 'home:group_view' pk=group.id %}">
                      <button type="button" class="btn cur-p btn-outline-primary">{% trans "View" %}</button>
                    </a>
                  </div>
                  <div class="peer">
                    <a href="{% url 'home:update_group' pk=group.id %}">
                      <button type="button" class="btn cur-p btn-outline-success">{% trans "Update" %}</button>
                    </a>
                  </div>
                  
                </div>
              </td>
            </tr>
            <!-- Delete Modal -->
            <div class="modal fade" id="delete-modal{{emp.emp_id.pk}}" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-body">
                    <p>{% trans "Are you sure you want to delete this record?" %}</p>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans "No" %}</button>
                    <a href="{% url 'employee:delete-employee' pk=group.pk %}" class="btn btn-danger" type="button">{% trans "Delete" %}</a>
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>


{% endblock body%}

home/templates/index_user.html
{% extends 'master.html'%}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load l10n %}
{% load i18n %}

{% block body %}

<div class="container-fluid">
  <div class="row gap-20 masonry pos-r">
    <div class="masonry-sizer col-md-6"></div>
    <div class="masonry-item w-100">
      <div class="row gap-20">
        <div class="col-md-4">
          <div class="layers bd bgc-white p-20">
            <div class="layer w-100 mB-10">
              <a href="{% url 'leave:list_leave' %}" class="card-link">
                <h6 class="lh-1">Leaves</h6>
              </a>
            </div>
            <div class="layer w-100">
              <div class="peers ai-sb fxw-nw">
                <div class="peer peer-greed">
                  <span id="sparklinedash2"><canvas width="45" height="20" style="display: inline-block; width: 45px; height: 20px; vertical-align: top;"></canvas></span></div>
                <div class="peer">
                  <span class="d-ib lh-0 va-m fw-600 bdrs-10em pX-15 pY-15 bgc-red-50 c-red-500">{{count_leaves}}</span>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="layers bd bgc-white p-20">
            <div class="layer w-100 mB-10">
              <h6 class="lh-1">Birthdays in the month of {% now "F" %}</h6>
            </div>
            <div class="layer w-100">
              <div class="peers ai-sb fxw-nw">
                <div class="peer peer-greed">
                  <span id="sparklinedash3">
                    <canvas width="45" height="20" style="display: inline-block; width: 45px; height: 20px; vertical-align: top;"></canvas></span></div>
                <div class="peer">
                  <span class="d-ib lh-0 va-m fw-600 bdrs-10em pX-15 pY-15 bgc-purple-50 c-purple-500">{{count_birthdays}}</span>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="layers bd bgc-white p-20">
            <div class="layer w-100 mB-10">
              <a href="#" class="card-link">
                <h6 class="lh-1">Notifications</h6>
              </a>
            </div>
            <div class="layer w-100">
              <div class="peers ai-sb fxw-nw">
                <div class="peer peer-greed">
                  <span id="sparklinedash3">
                    <canvas width="45" height="20" style="display: inline-block; width: 45px; height: 20px; vertical-align: top;"></canvas></span></div>
                <div class="peer">
                  <span class="d-ib lh-0 va-m fw-600 bdrs-10em pX-15 pY-15 bgc-purple-50 c-purple-500">{{count_notifications}}</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

<div class="row gap-20 masonry pos-r">
    <div class="masonry-item col-md-12">
      <div class="bgc-white bd bdrs-3 p-20 mB-20">
        <table class="table table-striped table-bordered" id="dataTable1" width="100%">
          <h5>Birthday in this month</h5>
          <thead>
            <tr>
              <th>#</th>
              <th>{% trans "Staff" %}</th>
              <th>{% trans "Birth Date" %}</th>
            </tr>
          </thead>
          <tbody>
            {% for employee in birthdays %}
            <tr>
              <td scope="row">{{ forloop.counter }}</td>
              <td>{{ employee.emp_name}}</td>
              <td>{{ employee.date_of_birth}}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  <div class="masonry-item col-md-12" >
    <div class="row">
       <div class="col-md-12">
          <div class="bgc-white bd bdrs-3 p-20">
             <table class="table table-hover table-striped table-bordered" id="dataTable" width="100%">
                <h5 class="lh-1">Todo List</h5>
                <thead>
                   <tr>
                      <th scope="col">Notification Title</th>
                      <th scope="col">Notification Body</th>
                      <th scope="col">Type</th>
                      <th scope="col">Date & Time</th>
                      <th scope="col">Status</th>
                       <th scope="col">Action</th>
                   </tr>
                </thead>
                <tbody>
                {% for notice in my_notifications %}
                   <tr>
                      <th scope="row">{{ notice.data.data.title }}</th>
                      <td>{{ notice.description}}</td>
                      <td>{{ notice.level }}</td>
                      <td><span class="badge bgc-red-50 c-red-700 p-10 lh-0 tt-c badge-pill"> {{ notice.timestamp }} </span></td>
                      <td><span class="badge bgc-green-50 c-green-700 p-10 lh-0 tt-c badge-pill">{{ notice.data.data.status }}</span></td>
                      <td>  {% if notice.data.data.href %}<a href="{% url notice.data.data.href id=notice.action_object_object_id %}">view request</a>{% endif %}</td>
                   </tr>
                   {% endfor %}
                </tbody>
             </table>
          </div>
       </div>
    </div>
 </div>
    <div class="masonry-item col-md-12">
      <div class="bgc-white bd bdrs-3 p-20 mB-20">
        <table class="table table-striped table-bordered" id="dataTable" width="100%">
          <h5>Notifications Table</h5>
          <thead>
            <tr>
              <th>#</th>
              <th>From</th>
              <th>Message</th>
              <th>Time</th>
            </tr>
          </thead>
          <tbody>
            {% for i in notifications %}
            <tr>
              <td>{{forloop.counter}}</td>
              <td><a href="#">{{i.from_emp}}</a></td>
              <td>{{i.message}}</td>
              <td>{{i.timestamp}}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <div class="bgc-white bd bdrs-3 p-20 mB-20">
    <table class="table table-striped table-bordered" id="dataTable" width="100%">
      <h5>Pending Service Requests</h5>
      <thead>
        <tr>
          <th>#</th>
          <th>Employee</th>
          <th> &nbsp Department </th>
          <th> &nbsp Destination</th>
          <th> &nbsp Project Name/Client Name</th>
          <th> &nbsp Status</th>
        </tr>
      </thead>
      <tbody>
        {% for i in bussiness_travel_service %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>{{i.emp}}</td>
          <td>&nbsp {{i.department}}</td>
          <td>&nbsp {{i.destination}}</td>
          <td>&nbsp {{i.project_name}}</td>
          <td>&nbsp {{i.status}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <i class="fa fa-star"></i>
    <a href="{% url 'service:services_create' %}">Request a Service</a>
  </div>


</div>


{% endblock body %}

home/templates/user-companies.html
<!DOCTYPE html>
{% load staticfiles %}
{% load i18n %}
{% load l10n %}
{% get_current_language as LANGUAGE_CODE %}
{% get_current_language_bidi as LANGUAGE_BIDI %}

<html {% if LANGUAGE_BIDI %} dir="rtl" {% else %} dir="ltr" {% endif %}>
<meta content="text/html;charset=UTF-8" />

<head>
  <title>PeopleM8 {% trans "Login" %}</title>

  {% if LANGsUAGE_BIDI %}
  <link href="{% static 'css/style-main-ar.css'%}" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Cairo&display=swap" rel="stylesheet">
  {% else %}
  <link href="{% static 'css/style-main-en.css'%}" rel="stylesheet">
  {% endif %}
  <link href="{% static 'css/style.css'%}" rel="stylesheet">
  <!-- datatable -->


</head>

<body class="app">
  <div id="loader">
    <div class="spinner"></div>
  </div>
  <script type="text/javascript">
    window.addEventListener('load', () => {
      const loader = document.getElementById('loader');
      setTimeout(() => {
        loader.classList.add('fadeOut');
      }, 300);
    });
  </script>
  <div class="peers ai-s fxw-nw h-100vh">
    <div class="d-n@sm- peer peer-greed h-100 pos-r bgr-n bgpX-c bgpY-c bgsz-cv" style="background-image:url({% static 'assets/static/images/bg4.jpg'%})">
      <div class="pos-a centerXY">
        <div class="bgc-white bdrs-50p pos-r" style="width:120px;height:120px"><img class="pos-a centerXY" src="{% static 'assets/static/images/logo.png'%}" alt=""></div>
      </div>
    </div>
    {% if LANGUAGE_BIDI %}
    <div class="col-12 col-md-4 peer pY-80 h-100 bgc-white scrollable pos-r text-right" style="min-width:320px;padding-left:40px;padding-right:40px">
      {%else%}
    <div class="col-12 col-md-4 peer pX-40 pY-80 h-100 bgc-white scrollable pos-r" style="min-width:320px">
      {% endif %}
      <h4 class="fw-300 c-grey-900 mB-40">{% trans "Login" %}</h4>
      <!--  -->
      <form method="POST">
        {% csrf_token %}
        <div class="form-group">
          <label class="text-normal text-dark">{% trans "User Name" %}</label>
          <input class="form-control" type="text" name="username" placeholder="{% trans "User Name" %}" required="required">
        </div>
        <div class="form-group">
          <label class="text-normal text-dark">{% trans "Password" %}</label>
          <input class="form-control" type="password" name="password" placeholder="{% trans "Password" %}" required="required">
        </div>
        <div class="form-group">
          <div class="peers ai-c jc-sb fxw-nw">
            <div class="peer">
              <button type="submit" class="btn btn-primary btn-block">{% trans "Log In" %}</button>
            </div>
          </div>
          <div class="row mT-40 text-center">
            <div class="col-md-12">
              {% if LANGUAGE_BIDI%}
              <a class="forgot pull-left" href="{% url 'home:en' %}">{% trans "English" %} </a>
              {%else%}
              <a class="forgot pull-right" href="{% url 'home:ar' %}">{% trans "English" %} </a>
              {%endif%}
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>

  <!-- jQuery -->
  <script src="{% static 'jquery/jquery.min.js'%}"></script>
  <script type="text/javascript" src="{% static 'js/vendor.js'%}"></script>
  {% if LANGUAGE_BIDI %}
  <script type="text/javascript" src="{% static 'js/bundleAr.js'%}"></script>
  {% else %}
  <script type="text/javascript" src="{% static 'js/bundle.js'%}"></script>
  {% endif %}
  <script src="{% static 'js/rocket-loader.min.js' %}" data-cf-settings="b7f1894beadbd64bfa501e09-|49" defer=""></script>
  <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.20/datatables.min.js"></script>
  {% block js %} {% endblock js %}
</body>

</html>

home/templates/user_group_list.html
{% extends 'master.html'%}
{% load staticfiles%}
{% load crispy_forms_tags %}
{% load l10n %}
{% load i18n %}
{% block body%}


<div class="row" style="margin-left:0px;">
    <div class="col-md-8">
        <h4 class="c-grey-900">{{page_title|title}}</h4>
    </div>
    <div class="col-md-4">
        <div class="gap-10 peers {% if LANGUAGE_BIDI %} push-left {% else %} push-right {% endif %}">
            <div class="peer"><a href="{% url 'home:assign_user' %}" class="btn cur-p btn-primary">{% trans "Add"%}</a></div>
            <!-- <div class="peer"><a href="{% url 'employee:list-employee-card' %}" class="btn cur-p btn-secondary">{% trans "Card View" %}</a></div> -->
        </div>
    </div>
</div>
<div class="row" style="margin-left:0px;">
    <div class="col-md-12">
        <div class="bgc-white bd bdrs-3 p-20 mB-20">
            <table class="table table-striped table-bordered" cellspacing="0" id="dataTable" width="100%">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>group</th>
                        <th width="30%">{% trans "Actions" %}</th>
                    </tr>
                </thead>
                <tbody>
                    {% for user in users %}
                    {% if user.groups.first != None %}
                    <tr>
                        <td scope="row">{{ forloop.counter }}</td>
                        <td>{{ user }}</td>
                        <td>{{ user.groups.first }}</td>
                        <td class="Actions">
                            <div class="peer">
                                <a href="{% url 'home:update_group' pk=user.id %}">
                                    <button type="button" class="btn cur-p btn-outline-success">{% trans "Update"%}</button>
                                </a>
                            </div>
                            <div class="w-100 gap-10 peers">
                                <div class="peer">
                                    <a href="{% url 'home:reset_user_group' pk=user.id %}">
                                        <button type="button" class="btn cur-p btn-outline-danger">{% trans "Delete"%}</button>
                                    </a>
                                </div>

                            </div>
                        </td>
                    </tr>
                    {% endif %}
                    <!-- Delete Modal -->
                    <div class="modal fade" id="delete-modal{{emp.emp_id.pk}}" tabindex="-1" role="dialog"
                        aria-hidden="true" style="display: none;">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-body">
                                    <p>{% trans "Are you sure you want to delete this record?" %}</p>
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans "No"
                                        %}</button>
                                    <a href="{% url 'employee:delete-employee' pk=user.pk %}" class="btn btn-danger"
                                        type="button">{% trans "Delete" %}</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>


{% endblock body%}