MashreqPayroll/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
import notifications.urls

urlpatterns = [
                  path('i18n/', include('django.conf.urls.i18n')),
                  path('arkleab4superadmin/', admin.site.urls),
                  path('', include('home.urls'), name='home'),
                  path('currencies/', include('currencies.urls')),
                  path('com/', include('company.urls')),
                  path('emp/', include('employee.urls')),
                  path('defenition/', include('defenition.urls')),
                  path('manage/', include('manage_payroll.urls')),
                  path('payroll/', include('payroll_run.urls')),
                  path('element/', include('element_definition.urls')),
                  path('costing/', include('balanc_definition.urls')),
                  path('leave/', include('leave.urls')),
                  path('attendance/', include('attendance.urls')),
                  path('report/', include('report.urls')),
                  path('recruitment/', include('recruitment.urls')),
                  path('service/', include('service.urls')),
                  path('tasks/', include('task_management.urls')),
                  path('perf/', include('performance.urls')),
                  path('inbox/notifications/', include(notifications.urls, namespace='notifications')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += i18n_patterns (
#
# )

home/urls.py
from django.urls import path, include
from home import views
from django.contrib.auth import views as auth_views
from django.conf.urls.i18n import i18n_patterns

app_name = 'home'

urlpatterns=[
        path('en/', views.viewEN, name='en'),
        path('ar/', views.viewAR, name='ar'),
        path('login/', views.user_login, name='user-login'),
        path('logout/', views.user_logout, name='logout'),
        path('register/', views.register, name='register'),
        path('add-user/', views.addUserView, name='new-user'),
        path('', views.homepage, name='homepage'),
        # path('', views.pie_chart, name='pie-chart'),
        path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
          name='password_change_done'),

        path('password_change/', views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
          name='password_change'),

        path('password_reset/done/', views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
        name='password_reset_done'),

        path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
        path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

        path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
        name='password_reset_complete'),
        #groups
        path('groups/',include([
            path('',views.group_list,name='group_list'),
            path('<int:pk>/',views.group_view,name='group_view'),
            path('new/',views.create_groups,name='create_group'),
            path('update/<int:pk>',views.edit_groups,name='update_group'),
            path('assign/',views.assign_role,name='assign_user'),
            path('users/',views.user_group_list,name="user_groups"),
            path('<int:pk>/delete',views.user_group_delete, name='reset_user_group')

        ])),
]

manage_payroll/urls.py
from django.urls import path
from manage_payroll import views

app_name ='manage_payroll'

urlpatterns=[
    ######################### AssignmentBatch URLs ###################################
    path('assignment/batch/new/', views.createAssignmentBatchView, name='assignBatch-create'),
    path('assignment/batch/list/', views.listAssignmentBatchView , name='list-assignBatch'),
    path('assignment/batch/update/<int:pk>/', views.updateAssignmentBatchView, name='update-assignBatch'),
    path('assignment/batch/delete/<int:pk>/', views.deleteAssignmentBatchView, name='delete-assignBatch'),
    ######################### Payment URLs ###################################
    path('payment/new/', views.createPaymentView, name='payment-type-create'),
    path('payment/list/', views.listPaymentView , name='list-payments'),
    path('payment/update/<int:pk>/', views.updatePaymentView , name='update-payment'),
    path('payment/correct/<int:pk>/', views.correctPaymentView , name='correct-payment'),
    path('payment/delete/<int:pk>/', views.deletePaymentView , name='delete-payment'),
    ######################### Bank&Bank_Branch URLs ###################################
    path('bank/new/', views.createBankAccountView, name='bank-create'),
    path('bank/list/', views.listBankAccountsView, name='list-banks'),
    path('bank/update/<int:pk>/', views.updateBankAccountView, name='update-bank'),
    path('bank/delete/<int:pk>/', views.deleteBankAccountView, name='delete-bank'),

    ######################### Payroll URLs ###################################
    path('payroll/new/', views.createPayrollView, name='payroll-create'),
    path('payroll/list/', views.listPayrollView, name='list-payroll'),
    path('payroll/update/<int:pk>/', views.updatePayrollView, name='update-payroll'),
    path('payroll/delete/<int:pk>/', views.deletePayrollView, name='delete-payroll'),
]

manage_payroll/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404 , HttpResponse
from django.contrib.auth.decorators import login_required
from datetime import date
from django.db.models import Q
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.utils.translation import to_locale, get_language
from django.utils.translation import ugettext_lazy as _
from manage_payroll.models import (Assignment_Batch, Assignment_Batch_Exclude,
                                   Assignment_Batch_Include, Payment_Type, Payment_Method,
                                   Bank_Master, Payroll_Master)
from manage_payroll.forms import (AssignmentBatchForm, BatchIncludeFormSet,
                                  BatchExcludeFormSet, Payment_Type_Form, Payment_Method_Form,
                                  PaymentMethodInline, Bank_MasterForm, PayrollMasterForm)


@login_required(login_url='home:user-login')
def listAssignmentBatchView(request):
    batch_list = Assignment_Batch.objects.all().filter((Q(end_date__gte=date.today())|Q(end_date__isnull=True)))
    batchContxt = {"page_title":_("Assignment Batchs") , 'batch_list': batch_list}
    return render(request, 'list-assignment-batch.html', batchContxt)


@login_required(login_url='home:user-login')
def createAssignmentBatchView(request):
    batch_form = AssignmentBatchForm()
    batch_include_form = BatchIncludeFormSet(
        queryset=Assignment_Batch_Include.objects.none())
    batch_exclude_form = BatchExcludeFormSet(
        queryset=Assignment_Batch_Exclude.objects.none())
    if request.method == 'POST':
        batch_form = AssignmentBatchForm(request.POST)
        batch_include_form = BatchIncludeFormSet(request.POST)
        batch_exclude_form = BatchExcludeFormSet(request.POST)
        if batch_form.is_valid() and batch_include_form.is_valid() and batch_exclude_form.is_valid():
            batch_form_obj = batch_form.save(commit=False)
            batch_form_obj.created_by = request.user
            batch_form_obj.last_update_by = request.user
            batch_form_obj.save()
            batch_include_form = BatchIncludeFormSet(
                request.POST, instance=batch_form_obj)
            batch_include_obj = batch_include_form.save(commit=False)
            for x in batch_include_obj:
                x.created_by = request.user
                x.last_update_by = request.user
                x.save()
            batch_exclude_form = BatchExcludeFormSet(
                request.POST, instance=batch_form_obj)
            batch_exclude_obj = batch_exclude_form.save(commit=False)
            for x in batch_exclude_obj:
                x.created_by = request.user
                x.last_update_by = request.user
                x.save()
                user_lang=user_lang=to_locale(get_language())
                if user_lang=='ar':
                    success_msg = 'تمت العملية بنجاح'
                else:
                    success_msg ='Create Successfully'
            # success_msg = 'Assignment Batch {}, has been created successfully'.format(
                # batch_form_obj.assignment_name)
                messages.success(request, success_msg)
            return redirect('manage_payroll:list-assignBatch')
        else:
            if batch_form.has_error:
                messages.error(request, batch_form.errors)
            elif batch_exclude_form.has_error:
                messages.error(request, batch_exclude_form.errors)
            elif batch_include_form.has_error:
                messages.error(request, batch_include_form.errors)
    batchContext = {
        "page_title": _("Create new Assignment Batch"),
        'batch_form': batch_form,
        'batch_include_form': batch_include_form,
        'batch_exclude_form': batch_exclude_form
    }
    return render(request, 'create-assignment-batch.html', batchContext)


@login_required(login_url='home:user-login')
def updateAssignmentBatchView(request, pk):
    required_assignment_batch = Assignment_Batch.objects.get(pk=pk)
    batch_form = AssignmentBatchForm(instance=required_assignment_batch)
    batch_include_form = BatchIncludeFormSet(
        instance=required_assignment_batch)
    batch_exclude_form = BatchExcludeFormSet(
        instance=required_assignment_batch)
    if request.method == 'POST':
        batch_form = AssignmentBatchForm(
            request.POST, instance=required_assignment_batch)
        batch_include_form = BatchIncludeFormSet(
            request.POST, instance=required_assignment_batch)
        batch_exclude_form = BatchExcludeFormSet(
            request.POST, instance=required_assignment_batch)
        if batch_form.is_valid() and batch_include_form.is_valid() and batch_exclude_form.is_valid():
            batch_form_obj = batch_form.save(commit=False)
            batch_form_obj.last_update_by = request.user
            batch_form_obj.save()
            batch_include_obj = batch_include_form.save(commit=False)
            for x in batch_include_obj:
                x.created_by = request.user
                x.last_update_by = request.user
                x.save()
            batch_exclude_obj = batch_exclude_form.save(commit=False)
            for x in batch_exclude_obj:
                x.created_by = request.user
                x.last_update_by = request.user
                x.save()
                user_lang=user_lang=to_locale(get_language())
                if user_lang=='ar':
                    success_msg = 'تمت العملية بنجاح'
                else:
                    success_msg ='Create Successfully'
            # success_msg = 'Assignment Batch {}, has been created successfully'.format(
                # batch_form_obj.assignment_name)

                messages.success(request, success_msg)
            return redirect('manage_payroll:list-assignBatch')
        else:
            if batch_form.has_error:
                messages.error(request, batch_form.errors)
            elif batch_exclude_form.has_error:
                messages.error(request, batch_exclude_form.errors)
            elif batch_include_form.has_error:
                messages.error(request, batch_include_form.errors)
    batchContext = {
        "page_title": _("update Assignment Batch"),
        'batch_form': batch_form,
        'batch_include_form': batch_include_form,
        'batch_exclude_form': batch_exclude_form
    }
    return render(request, 'create-assignment-batch.html', batchContext)


@login_required(login_url='home:user-login')
def deleteAssignmentBatchView(request, pk):
    required_assignment_batch = get_object_or_404(Assignment_Batch, pk=pk)
    try:
        batch_form = AssignmentBatchForm(instance=required_assignment_batch)
        batch_obj = batch_form.save(commit=False)
        batch_obj.end_date = date.today()
        batch_include_form = BatchIncludeFormSet(
            instance=required_assignment_batch)
        batch_include_obj = batch_include_form.save(commit=False)
        for x in batch_include_obj:
            x.end_date = date.today()
            x.save(update_fields=['end_date'])
        batch_exclude_form = BatchExcludeFormSet(
            instance=required_assignment_batch)
        batch_exclude_obj = batch_exclude_form.save(commit=False)
        for x in batch_exclude_obj:
            x.end_date = date.today()
            x.save(update_fields=['end_date'])
        batch_obj.save(update_fields=['end_date'])
        user_lang=to_locale(get_language())
        if user_lang=='ar':
            success_msg = '{}تم حذف '.format(required_assignment_batch)
        else:
            success_msg = '{} was deleted successfully '.format(required_assignment_batch)
        # success_msg = '{} was deleted successfully'.format(
            # required_assignment_batch)
        messages.success(request, success_msg)
    except Exception as e:
        user_lang=user_lang=to_locale(get_language())
        if user_lang=='ar':
            error_msg = '{} لم يتم حذف '.format(required_assignment_batch)
        else:
            error_msg = '{} cannot be deleted '.format(required_assignment_batch)
        # error_msg = '{} cannot be deleted '.format(required_assignment_batch)
            messages.error(request, error_msg)
        raise e
    return redirect('manage_payroll:list-assignBatch')

###############################################################################
#               Payment type & method inline form
###############################################################################
@login_required(login_url='home:user-login')
def createPaymentView(request):
    payment_type_form = Payment_Type_Form()
    payment_method_inline = PaymentMethodInline()
    if request.method == 'POST':
        payment_type_form = Payment_Type_Form(request.POST)
        payment_method_inline = PaymentMethodInline(request.POST)
        if payment_type_form.is_valid() or payment_method_inline.is_valid():
            payment_object = payment_type_form.save(commit=False)
            payment_object.enterprise = request.user.company
            payment_object.created_by = request.user
            payment_object.last_update_by = request.user
            payment_object.save()
            payment_method_inline = PaymentMethodInline(
                request.POST, instance=payment_object)
            if payment_method_inline.is_valid():
                inline_obj = payment_method_inline.save(commit=False)
                for row in inline_obj:
                    row.created_by = request.user
                    row.last_update_by = request.user
                    row.save()
            user_lang=user_lang=to_locale(get_language())
            if user_lang=='ar':
                success_msg = 'تمت العملية بنجاح'
            else:
                success_msg ='Create Successfully'
            messages.success(request, success_msg)
        else:
            messages.error(request, _('Payment form hase invalid data'))

manage_payroll/templates/list-assignment-batch.html
{% extends 'master.html'%}
{% load staticfiles%}
{% load crispy_forms_tags %}
{% load l10n %}
{% load i18n %}
{% block body%}

<div class="container-fluid">
  <div class="row" style="margin-left:0px;">
    <div class="col-md-8">
      <h4 class="c-grey-900">{{page_title|title}}</h4>
    </div>
    <div class="col-md-4">
      <div class="gap-10 peers {% if LANGUAGE_BIDI %} push-left {% else %} push-right {% endif %}">
        <div class="peer" data-toggle="tooltip" data-placement="bottom" title="{% trans 'Add' %}">
          <a href="{% url 'manage_payroll:assignBatch-create' %}" class="btn cur-p btn-primary">
            <i class="fas fa-plus-square"></i>
          </a>
        </div>
      </div>
    </div>
  </div>
  <div class="row" style="margin-left:0px;">
    <div class="col-md-12">
      <div class="bgc-white bd bdrs-3 p-20 mB-20">
        <table class="table table-striped table-bordered" id="dataTable"  width="100%">
          <thead>
            <tr>
              <th>#</th>
              <th>{% trans "Assignment Name" %}</th>
              <th>{% trans "Code" %}</th>
              <th>{% trans "Payroll name" %}</th>
              <th>{% trans "Actions" %}</th>
            </tr>
          </thead>
          <tbody>
            {% for batch in batch_list %}
            <tr>
              <th scope="row">{{ forloop.counter }}</th>
              <td>{{ batch.assignment_name }}</td>
              <td>{{ batch.assignment_code }}</td>
              <td>{{ batch.payroll_id }}</td>
              <td class="Actions">
                <div class="w-100 gap-10 peers">
                  <div class="peer" data-toggle="tooltip" data-placement="bottom" title="{% trans 'Update' %}">
                    <a href="{% url 'manage_payroll:update-assignBatch' pk=batch.id %}">
                      <button type="button" class="btn cur-p btn-outline-primary">&#9997</button>
                    </a>
                  </div>
                  <div class="peer" data-toggle="tooltip" data-placement="bottom" title="{% trans 'Delete' %}">
                    <a href="#">
                      <button type="button" class="btn cur-p btn-outline-danger" data-toggle="modal" data-target="#delete-modal{{batch.pk}}">&#128465</button>
                    </a>
                  </div>
                </div>
              </td>
            </tr>
          <div class="modal fade" id="delete-modal{{batch.pk}}" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">{% trans "Delete " %}</h5>
                </div>
                <div class="modal-body">
                  <p>{% trans "Are you sure you want to delete this record?" %}</p>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-outline-secondary" data-dismiss="modal"
                          data-toggle="tooltip" data-placement="bottom" title="{% trans 'Cancel' %}">&#x2718</button>
                  <a href="{% url 'manage_payroll:delete-assignBatch' pk=batch.pk %}" class="btn btn-outline-danger" type="button"
                          data-toggle="tooltip" data-placement="bottom" title="{% trans 'Delete' %}">&#128465</a>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
        </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock body%}

manage_payroll/templates/list-bank-branchs.html
{% extends 'master.html'%}
{% load staticfiles%}
{% load crispy_forms_tags %}
{% load l10n %}
{% load i18n %}
{% block body%}

<div class="container-fluid">
  <div class="row" style="margin-left:0px;">
    <div class="col-md-8">
      <h4 class="c-grey-900">{{page_title|title}}</h4>
    </div>
    <div class="col-md-4">
      <div class="gap-10 peers {% if LANGUAGE_BIDI %} push-left {% else %} push-right {% endif %}">
        <div class="peer" data-toggle="tooltip" data-placement="bottom" title="{% trans 'Add' %}">
          <a href="{% url 'manage_payroll:bank-create' %}" class="btn cur-p btn-primary">
            <i class="fas fa-plus-square"></i>
          </a>
        </div>
      </div>
    </div>
  </div>
  <div class="row" style="margin-left:0px;">
    <div class="col-md-12">
      <div class="bgc-white bd bdrs-3 p-20 mB-20">
        <table class="table table-striped table-bordered" id="dataTable"  width="100%">
          <thead>
            <tr>
              <th>#</th>
              <th>{% trans "Bank Name" %}</th>
              <th>{% trans "Branch Name" %}</th>
              <th>{% trans "Currency" %}</th>
              <th>{% trans "Actions" %}</th>
            </tr>
          </thead>
          <tbody>
            {% for x in bank_master %}
            <tr>
              <th scope="row">{{ forloop.counter }}</th>
              <td>{{ x.bank_name }}</td>
              <td>{{ x.branch_name }}</td>
              <td>{{ x.currency }}</td>
              <td class="Actions">
                <div class="w-100 gap-10 peers">
                  <div class="peer" data-toggle="tooltip" data-placement="bottom" title="{% trans 'Update' %}">
                    <a href="{% url 'manage_payroll:update-bank' pk=x.id %}">
                      <button type="button" class="btn cur-p btn-outline-primary">&#9997</button>
                    </a>
                  </div>
                  <div class="peer" data-toggle="tooltip" data-placement="bottom" title="{% trans 'Delete' %}">
                    <a href="#">
                      <button type="button" class="btn cur-p btn-outline-danger" data-toggle="modal" data-target="#delete-modal{{x.pk}}">&#128465</button>
                    </a>
                  </div>
                </div>
              </td>
            </tr>
          <div class="modal fade" id="delete-modal{{x.pk}}" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">{% trans "Delete " %}</h5>
                </div>
                <div class="modal-body">
                  <p>{% trans "Are you sure you want to delete this record?" %}</p>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-outline-secondary"
                          data-dismiss="modal" data-toggle="tooltip" data-placement="bottom" title="{% trans 'Cancel' %}">&#x2718</button>
                  <a href="{% url 'manage_payroll:delete-bank' pk=x.id %}" class="btn btn-outline-danger" type="button"
                     data-toggle="tooltip" data-placement="bottom" title="{% trans 'Delete' %}">&#128465</a>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
        </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock body%}

manage_payroll/templates/list-payrolls.html
{% extends 'master.html'%}
{% load staticfiles%}
{% load crispy_forms_tags %}
{% load l10n %}
{% load i18n %}
{% block body%}

<div class="container-fluid">
  <div class="row" style="margin-left:0px;">
    <div class="col-md-8">
      <h4 class="c-grey-900">{{page_title|title}}</h4>
    </div>
    <div class="col-md-4">
      <div class="gap-10 peers {% if LANGUAGE_BIDI %} push-left {% else %} push-right {% endif %}">
        <div class="peer" data-toggle="tooltip" data-placement="bottom" title="{% trans 'Add' %}">
          <a href="{% url 'manage_payroll:payroll-create' %}" class="btn cur-p btn-primary">
            <i class="fas fa-plus-square"></i>
          </a>
        </div>
      </div>
    </div>
  </div>
  <div class="row" style="margin-left:0px;">
    <div class="col-md-12">
      <div class="bgc-white bd bdrs-3 p-20 mB-20">
        <table class="table table-striped table-bordered" id="dataTable"  width="100%">
          <thead>
            <tr>
              <th>#</th>
              <th>{% trans "Payroll Name" %}</th>
              <th>{% trans "Type" %}</th>
              <th>{% trans "Actions" %}</th>
            </tr>
          </thead>
          <tbody>
            {% for x in list_payroll %}
            <tr>
              <th scope="row">{{ forloop.counter }}</th>
              <td>{{ x.payroll_name }}</td>
              <td>{{ x.period_type }}</td>
              <td class="Actions">
                <div class="w-100 gap-10 peers">
                  <div class="peer" data-toggle="tooltip" data-placement="bottom" title="{% trans 'Update' %}">
                    <a href="{% url 'manage_payroll:update-payroll' pk=x.id %}">
                      <button type="button" class="btn cur-p btn-outline-primary">&#9997</button>
                    </a>
                  </div>
                  <div class="peer" data-toggle="tooltip" data-placement="bottom" title="{% trans 'Delete' %}">
                    <a href="#">
                      <button type="button" class="btn cur-p btn-outline-danger" data-toggle="modal" data-target="#delete-modal{{x.pk}}">&#128465</button>
                    </a>
                  </div>
                </div>
              </td>
            </tr>
          <div class="modal fade" id="delete-modal{{x.pk}}" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">{% trans "Delete " %}</h5>
                </div>
                <div class="modal-body">
                  <p>{% trans "Are you sure you want to delete this record?" %}</p>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-outline-secondary" data-dismiss="modal"
                          data-toggle="tooltip" data-placement="bottom" title="{% trans 'Cancel' %}">&#x2718</button>
                  <a href="{% url 'manage_payroll:delete-payroll' pk=x.id %}" class="btn btn-outline-danger" type="button"
                     data-toggle="tooltip" data-placement="bottom" title="{% trans 'Delete' %}">&#128465</a>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
        </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock body%}

manage_payroll/templates/payment-list.html
{% extends 'master.html'%}
{% load staticfiles%}
{% load crispy_forms_tags %}
{% load l10n %}
{% load i18n %}
{% block body%}

<div class="container-fluid">
  <div class="row" style="margin-left:0px;">
    <div class="col-md-8">
      <h4 class="c-grey-900">{{page_title|title}}</h4>
    </div>
    <div class="col-md-4">
      <div class="gap-10 peers {% if LANGUAGE_BIDI %} push-left {% else %} push-right {% endif %}">
        <div class="peer" data-toggle="tooltip" data-placement="bottom" title="{% trans 'Add' %}">
          <a href="{% url 'manage_payroll:payment-type-create' %}" class="btn cur-p btn-primary">
            <i class="fas fa-plus-square"></i>
          </a>
        </div>
      </div>
    </div>
  </div>
  <div class="row" style="margin-left:0px;">
    <div class="col-md-12">
      <div class="bgc-white bd bdrs-3 p-20 mB-20">
        <table class="table table-striped table-bordered" id="dataTable"  width="100%">
          <thead>
            <tr>
              <th>#</th>
              <th>{% trans "Type" %}</th>
              <th>{% trans "Payment Method" %}</th>
              <th>{% trans "Actions" %}</th>
            </tr>
          </thead>
          <tbody>
            {% for payment in payment_type_list %}
            <tr>
              <th>{{ forloop.counter }}</th>
              <td>{{ payment.type_name }}</td>
              <td>{{ payment.category }}</td>
              <td class="Actions">
                <div class="w-100 gap-10 peers">
                  <div class="peer" data-toggle="tooltip" data-placement="bottom" title="{% trans 'Update' %}">
                    <a href="{%url 'manage_payroll:update-payment' pk=payment.pk%}">
                      <button type="button" class="btn cur-p btn-outline-primary">&#9997</button>
                    </a>
                  </div>
                  <div class="peer" data-toggle="tooltip" data-placement="bottom" title="{% trans 'Correction' %}">
                    <a href="{%url 'manage_payroll:correct-payment' pk=payment.pk%}">
                      <button type="button" class="btn cur-p btn-outline-success">&#x270E</button>
                    </a>
                  </div>
                  <div class="peer" data-toggle="tooltip" data-placement="bottom" title="{% trans 'Delete' %}">
                    <a href="#">
                      <button type="button" class="btn cur-p btn-outline-danger" data-toggle="modal" data-target="#delete-modal{{payment.pk}}">&#128465</button>
                    </a>
                  </div>
                </div>
              </td>
            </tr>
          <div class="modal fade" id="delete-modal{{payment.pk}}" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">{% trans "Delete " %}</h5>
                </div>
                <div class="modal-body">
                  <p>{% trans "Are you sure you want to delete this record?" %}</p>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-outline-secondary" data-dismiss="modal"
                          data-toggle="tooltip" data-placement="bottom" title="{% trans 'Cancel' %}">&#x2718</button>
                  <a href="{%url 'manage_payroll:delete-payment' pk=payment.pk%}" class="btn btn-outline-danger" type="button"
                     data-toggle="tooltip" data-placement="bottom" title="{% trans 'Delete' %}">&#128465</a>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
        </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock body%}