MashreqPayroll/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
import notifications.urls

urlpatterns = [
                  path('i18n/', include('django.conf.urls.i18n')),
                  path('arkleab4superadmin/', admin.site.urls),
                  path('', include('home.urls'), name='home'),
                  path('currencies/', include('currencies.urls')),
                  path('com/', include('company.urls')),
                  path('emp/', include('employee.urls')),
                  path('defenition/', include('defenition.urls')),
                  path('manage/', include('manage_payroll.urls')),
                  path('payroll/', include('payroll_run.urls')),
                  path('element/', include('element_definition.urls')),
                  path('costing/', include('balanc_definition.urls')),
                  path('leave/', include('leave.urls')),
                  path('attendance/', include('attendance.urls')),
                  path('report/', include('report.urls')),
                  path('recruitment/', include('recruitment.urls')),
                  path('service/', include('service.urls')),
                  path('tasks/', include('task_management.urls')),
                  path('perf/', include('performance.urls')),
                  path('inbox/notifications/', include(notifications.urls, namespace='notifications')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += i18n_patterns (
#
# )

company/urls.py
from django.urls import path, include
from company import views

app_name = 'company'

urlpatterns = [
    ######################### BusinessGroup URLs ###################################
    path('user/companies/list/', views.list_user_companies_view, name='user-companies-list'),
    path('user/companies/create/', views.create_user_companies_view, name='user-companies-create'),
    path('user/companies/makeActive/<int:company_id>/', views.mark_as_active_view, name='user-company-active'),
    path('enterprise/', include([
        path('new/', views.companyCreateView, name='company-create'),
        path('information/list/', views.listCompanyInformation, name='list-company-information'),
        path('update/<int:pk>/', views.updateBusinessGroup, name='update-business-group'),
        path('delete/<int:pk>/', views.deleteBusinessGroup, name='delete-enterprise'),
    ])),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),
    path('setup/', views.load_modules, name='setup_company'),

    path('assinment/', include([
        ######################### Department URLs ###################################
        path('department/list/', views.listDepartmentView, name='list-department'),
        path('department/new/', views.createDepartmentView, name='department-create'),
        path('department/update/<int:pk>', views.updateDepartmentView, name='department-update'),
        path('department/view/<int:pk>', views.viewDepartmentView, name='department-view'),
        path('department/correct/<int:pk>', views.correctDepartmentView, name='department-correct'),
        path('department/delete/<int:pk>', views.deleteDepartmentView, name='department-delete'),
        path('department/export/', views.export_department_data, name='department-export'),
        path('hirarchy/', views.viewHirarchy, name='hirarchy'),
        ######################### Jobs URLs #########################################
        path('jobs/list/', views.listJobView, name='list-jobs'),
        path('job/new/', views.createJobView, name='job-create'),
        path('job/update/<int:pk>', views.updateJobView, name='job-update'),
        path('job/correct/<int:pk>', views.correctJobView, name='job-correct'),
        path('job/delete/<int:pk>', views.deleteJobView, name='job-delete'),
        path('job/export/', views.export_job_data, name='job-export'),

        ######################### Grades URLs #######################################
        path('grade/list/', views.listGradeView, name='list-grades'),
        path('grade/new/', views.createGradeView, name='grade-create'),
        path('grade/update/<int:pk>', views.updateGradeView, name='grade-update'),
        path('grade/correct/<int:pk>', views.correctGradeView, name='grade-correct'),
        path('grade/delete/<int:pk>', views.deleteGradeView, name='grade-delete'), 
        path('grade/export/', views.export_grade_data, name='grade-export'),

        ######################### Positions URLs ###################################
        path('positions/list/', views.listPositionView, name='list-positions'),
        path('position/new/', views.createPositionView, name='position-create'),
        path('position/update/<int:pk>', views.updatePositionView, name='position-update'),
        path('position/correct/<int:pk>', views.correctPositionView, name='position-correct'),
        path('position/delete/<int:pk>', views.deletePositionView, name='position-delete'),
        path('position/export/', views.export_position_data, name='position-export'),

    ])),
    ######################### Working Hours Policy URLs ###################################
    path('policies/', include([
        ######################### Department URLs ###################################
        path('years/list/', views.listYearsView, name='list-years'),
        path('working_hrs_policy/new/', views.CreateWorkingPolicyView, name='policy-create'),
        path('working_hrs_policy/list/', views.listWorkingPolicyView, name='working-hrs-policy-list'),
        path('working_hrs_policy/correct/<int:pk>', views.correctWorkingPolicyView, name='policy-correct'),
        path('yearly_holidays/list/<int:year_id>', views.listYearlyHolidayView, name='yearly-holiday-list'),
        path('yearly_holidays/create/<int:year_id>', views.createYearlyHolidayView, name='yearly-holiday-create'),
        path('yearly_holidays/correct/<int:pk>', views.correctYearlyHolidayView, name='yearly-holiday-correct'),
        path('yearly_holidays/delete/<int:pk>', views.deleteYearlyHolidayView, name='yearly-holiday-delete'),
        path('working_hrs_policy/delete/<int:pk>', views.deleteWorkingPolicyView, name='working-hrs-policy-delete'),

        path('working-hrs-deduction-policy/new/', views.create_working_hours_deductions_view, name='hours-deduction-policy-create'),
        path('working-hrs-deductions/list/', views.list_working_hours_deductions_view, name='working-hrs-deductions-list'),
        path('working-hrs-deductions/update/<int:deduction_id>', views.update_working_hours_deductions_view, name='working-hrs-deductions-update'),

    ]
    )),
]

employee/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from employee import views
from urllib.parse import quote
from django.utils.encoding import iri_to_uri, uri_to_iri

app_name= 'employee'

urlpatterns =[
    path('employee/', include([
            ######################### Employee URLs ###################################
            path('new/', views.createEmployeeView, name='employee-create'),
            path('element/', views.copy_element_values, name='element-create'),
            path('information/listT/', views.listEmployeeView , name='list-employee'),
            path('information/listC/', views.listEmployeeCardView , name='list-employee-card'),
            path('correct/<int:pk>/', views.correctEmployeeView, name='correct-employee'),
             path('update/<int:pk>/', views.updateEmployeeView, name='update-employee'),
            path('view/<int:pk>/', views.viewEmployeeView, name='view-employee'),
            path('delete/<int:pk>/', views.deleteEmployeeView, name='delete-employee'),
            path('delete/forever/<int:pk>/', views.deleteEmployeePermanently, name='delete-employee-permanently'),

            path('link/employee/<int:pk>/structure/', views.create_link_employee_structure, name='link-structure-create'),
            path('update/link/employee/<int:pk>/structure/', views.update_link_employee_structure, name='link-structure-update'),
            path('ajax/', views.change_element_value, name='change-element-value'),
            path('employee/export/', views.export_employee_data, name='employee-export'),
            path('jobroll/new/<int:job_id>', views.createJobROll, name='new-jobroll'),
            path('leaves-history/' , views.list_employee_leave_requests , name='leaves-history'),
            path('element/new/<int:job_id>', views.create_employee_element, name='new-employee-element'),





    ])),

]

home/urls.py
from django.urls import path, include
from home import views
from django.contrib.auth import views as auth_views
from django.conf.urls.i18n import i18n_patterns

app_name = 'home'

urlpatterns=[
        path('en/', views.viewEN, name='en'),
        path('ar/', views.viewAR, name='ar'),
        path('login/', views.user_login, name='user-login'),
        path('logout/', views.user_logout, name='logout'),
        path('register/', views.register, name='register'),
        path('add-user/', views.addUserView, name='new-user'),
        path('', views.homepage, name='homepage'),
        # path('', views.pie_chart, name='pie-chart'),
        path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
          name='password_change_done'),

        path('password_change/', views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
          name='password_change'),

        path('password_reset/done/', views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
        name='password_reset_done'),

        path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
        path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

        path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
        name='password_reset_complete'),
        #groups
        path('groups/',include([
            path('',views.group_list,name='group_list'),
            path('<int:pk>/',views.group_view,name='group_view'),
            path('new/',views.create_groups,name='create_group'),
            path('update/<int:pk>',views.edit_groups,name='update_group'),
            path('assign/',views.assign_role,name='assign_user'),
            path('users/',views.user_group_list,name="user_groups"),
            path('<int:pk>/delete',views.user_group_delete, name='reset_user_group')

        ])),
]

leave/urls.py
from django.urls import path
from leave import views

app_name = 'leave'

urlpatterns = [
    path('list_leave/', views.list_leave, name='list_leave'),
    path('del_leave/<int:id>', views.delete_leave_view, name='del_leave'),
    path('add_leave/', views.add_leave, name='add_leave'),
    path('edit_leave/<int:id>', views.edit_leave, name='edit_leave'),
    path('add_leave_master/', views.add_leave_master, name='add_leave_master'),
    path('list-leave-master/', views.list_leave_master, name='list-leave-master'),
    path('edit_leave_master/<int:id>', views.edit_leave_master, name='edit_leave_master'),
    path('del_leave_master/<int:id>', views.del_leave_master, name='del_leave_master'),
    path('leave-approve/<int:leave_id>/<str:redirect_to>/', views.leave_approve, name='leave-approve'),
    path('leave-unapprove/<int:leave_id>/<str:redirect_to>/', views.leave_unapprove, name='leave-unapprove'),
    path('leave-balance/', views.Elmplyees_Leave_Balance.as_view(), name='leave-balance'),

    path('leave-balance/edit/<int:leave_balance_id>/', views.edit_employee_leaves_balance, name='leave_balance_edit'),
    path('leave-balance/delete/<int:leave_balance_id>/', views.delete_leave_balance, name='leave_balance_delete'),

    path('leave-balance-add/', views.create_employee_leave_balance, name='leave-balance-create'),
    path('leave-balance-list/<int:employee_id>/', views.view_employee_leaves_list, name='employee-leave-list'),
    path('leave-type/', views.get_leave_type, name='leave_type'),

]

service/urls.py
from django.urls import path
from service import views

# TEMPLATE TAGGING
app_name = 'service'
urlpatterns = [
    path('bussiness/travel/list/', views.services_list, name='services_list'),
    path('bussiness/travel/delete/<int:id>', views.services_delete, name='services_delete'),
    path('bussiness/travel/edit/<int:id>', views.services_edit, name='services_edit'),
    path('bussiness/travel/update/<int:id>/', views.services_update, name='services-update'),
    path('services/create/', views.services_create, name='services_create'),
    path('service/approve/<int:service_id>/<str:redirect_to>', views.service_approve, name='service-approve'),
    path('service/unapprove/<int:service_id>/<str:redirect_to>', views.service_unapprove, name='service-unapprove'),

    path('purchase/list/', views.purchase_request_list, name='purchase-request-list'),
    path('purchase/order/create/', views.purchase_request_create, name='purchase-request-create'),
    path('purchase/order/update/<int:id>/', views.purchase_request_update, name='purchase-request-update'),
    path('purchase/approve/<int:order_id>', views.purchase_request_approve, name='purchase-approve'),
    path('purchase/unapprove/<int:order_id>', views.purchase_request_unapprove, name='purchase-unapprove'),
]

MashreqPayroll/views.py
from django.contrib.auth.decorators import login_required
from notifications.views import AllNotificationsList


# I cant find where or how to make the changes I want withing the app's views.py, but this is an example
@login_required
def custom_get_queryset(self):
    # custom logic here, changing all notifications to 'read'

    return custom_get_queryset(self)


from django.shortcuts import render

MashreqPayroll/templates/footer.html
{% load staticfiles %}

<footer class="bdT ta-c p-30 lh-0 fsz-sm c-grey-600">
  <span>Copyright © 2019 <a href="https://peoplem8.com/" target="_blank" title="PeopleM8">PeopleM8</a>. All rights reserved.</span>
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13" type="057b631b541ac41fa04fb5af-text/javascript"></script>
  <script type="text/javascript">
    window.dataLayer = window.dataLayer || [];

    function gtag() {
      dataLayer.push(arguments);
    }
    gtag('js', new Date());
    gtag('config', 'UA-23581568-13');
  </script>
</footer>

MashreqPayroll/templates/side_bar.html
{% load i18n %}
{% load l10n %}
{% load group_extra %}
{% load staticfiles %}
<div class="sidebar-inner">
  <div class="sidebar-logo">
    <div class="peers ai-c fxw-nw">
      <div class="peer peer-greed">
        <a class="sidebar-link td-n" href="{% url 'home:homepage' %}">
          <div class="peers ai-c fxw-nw">
            <div class="peer">
              <div class="logo"><img src="{% static 'assets/static/images/logo.png' %}" alt=""></div>
            </div>
            <div class="peer peer-greed">
              <h5 class="lh-1 mB-0 logo-text">PeopleM8</h5>
            </div>
          </div>
        </a>
      </div>
      <div class="peer">
        <div class="mobile-toggle sidebar-toggle"><a href="#" class="td-n"><i class="ti-arrow-circle-left"></i></a>
        </div>
      </div>
    </div>
  </div>
  <ul class="sidebar-menu scrollable pos-r">
    <li class="nav-item mT-30 active"><a class="sidebar-link" href="{% url 'home:homepage' %}" default>
        <span class="icon-holder"><i class="c-blue-500 ti-home"></i> </span>
        <span class="title">{% trans 'Dashboard'%}</span></a>
    </li>
    {% if request.user|has_group:"Admin"%}
    <li class="nav-item dropdown">
      <a class="dropdown-toggle" href="javascript:void(0);"><span class="icon-holder"><i class="c-orange-500 ti-layout-list-thumb"></i> </span><span class="title">{% trans 'Company Setup'%}</span>
        <span class="arrow"><i class="ti-angle-right"></i></span></a>
      <ul class="dropdown-menu">
        <li><a class="sidebar-link" href="{% url 'company:list-company-information' %}">{% trans 'Enterprise Information'%}</a></li>
        <!-- <li><a class="sidebar-link" href="{% url 'balanc_definition:list-cost-center' %}">{% trans 'Cost Center'%}</a> -->
    </li>

    <li class="nav-item dropdown">
      <a href="javascript:void(0);">
        <span>{% trans 'Enterprise structure'%}</span>
        <span class="arrow"><i class="ti-angle-right"></i></span>
      </a>
      <ul class="dropdown-menu" style="display: none;">
        <li><a href="{% url 'company:list-department' %}">{% trans "Departments" %}</a></li>
        <li><a href="{% url 'company:list-jobs' %}">{% trans "Jobs" %}</a></li>
        <li><a href="{% url 'company:list-grades' %}">{% trans "Grades" %}</a></li>
        <li><a href="{% url 'company:list-positions' %}">{% trans "Positions" %}</a></li>
      </ul>
    </li>
  </ul>

  {% if request.user.is_superuser %}
  <ul class="dropdown-menu">
    <li class="nav-item dropdown">
      <a href="javascript:void(0);">
        <span>{% trans 'Lookups Management'%}</span>
        <span class="arrow"><i class="ti-angle-right"></i></span>
      </a>
      <ul class="dropdown-menu" style="display: none;">
        <li><a class="sidebar-link" href="{% url 'company:setup_company' %}">{% trans 'Upload Modules'%}</a></li>
        <li><a class="sidebar-link" href="{% url 'defenition:list-lookups' %}">{% trans 'Lookup Details'%}</a></li>
      </ul>
    </li>
  </ul>
  {% endif %}


  <li class="nav-item dropdown">
    <a class="dropdown-toggle" href="javascript:void(0);"><span class="icon-holder"><i class="c-red-500 ti-files"></i>
      </span><span class="title">{% trans "Manage Payroll" %}</span> <span class="arrow"><i class="ti-angle-right"></i></span></a>
    <ul class="dropdown-menu">
      <li class="nav-item dropdown">
        <a class="dropdown-toggle" href="javascript:void(0);">
          <span class="title">{% trans 'Salary Management'%}</span> <span class="arrow"><i class="ti-angle-right"></i></span>
        </a>
        <ul class="dropdown-menu">
          <li><a class="sidebar-link" href="{% url 'element_definition:list-element' %}">{% trans 'Salary Details'%}</a>
          </li>
          <li><a class="sidebar-link" href="{% url 'element_definition:list-batchs' %}">{% trans 'Salary Structure'%}</a>
          </li>
        </ul>
      </li>

      <li><a class="sidebar-link" href="{% url 'manage_payroll:list-banks' %}">{% trans 'Banks and branches'%}</a></li>
      <li><a class="sidebar-link" href="{% url 'manage_payroll:list-payments' %}">{% trans 'Payments Setup'%}</a></li>
      <li><a class="sidebar-link" href="{% url 'manage_payroll:list-payroll' %}">{% trans 'Payroll Definitions'%}</a></li>
      <li><a class="sidebar-link" href="{% url 'defenition:tax-list' %}">{% trans 'Tax Rules'%}</a></li>
      <li><a class="sidebar-link" href="{% url 'payroll_run:list-salary' %}">{% trans 'Payroll Run' %}</a></li>
      <li><a class="sidebar-link" href="{% url 'manage_payroll:list-assignBatch' %}">{% trans 'Assignment Batch'%}</a></li>
    </ul>
  </li>
  <li class="nav-item dropdown">
    <a class="dropdown-toggle" href="javascript:void(0);"><span class="icon-holder"><i class="c-pink-500  ti-user"></i> </span><span class="title">{% trans "Employee Management" %}</span> <span class="arrow"><i class="ti-angle-right"></i></span></a>
    <ul class="dropdown-menu">
      <li><a class="sidebar-link" href="{% url 'employee:list-employee' %}">{% trans 'Personal & Job Information'%}</a></li>

    </ul>
  </li>
  {% endif %}

  {% if request.user|has_group:"Admin" or request.user|has_group:"Employee" %}
  <li class="nav-item dropdown">
    <a class="dropdown-toggle" href="javascript:void(0);"><span class="icon-holder"><i class="c-pink-500 ti-agenda"></i> </span><span class="title">{% trans "Employee Services" %}</span> <span class="arrow"><i class="ti-angle-right"></i></span></a>
    <ul class="dropdown-menu">
      {% if request.user|has_group:"Admin" or request.user|has_group:"HR" %}
      <li class="nav-item dropdown">
        <a class="dropdown-toggle" href="javascript:void(0);"><span class="icon-holder"></span><span class="title">{% trans "Employee Leaves" %}</span> <span class="arrow"><i class="ti-angle-right"></i></span></a>
        <ul class="dropdown-menu">
          <li><a class="sidebar-link" href="{% url 'leave:list_leave' %}">{% trans 'Leaves List'%}</a></li>
          <li><a class="sidebar-link" href="{% url 'employee:leaves-history' %}">{% trans 'Leaves Board'%}</a></li>
        </ul>
      </li>
      {% else %}
      <li><a class="sidebar-link" href="{% url 'leave:list_leave' %}">{% trans 'Employee Leaves'%}</a></li>
     {% endif %}
      <li><a class="sidebar-link" href="{% url 'service:services_list' %}">{% trans 'Bussiness Travel Form'%}</a></li>
      <li><a class="sidebar-link" href="{% url 'service:purchase-request-list' %}">{% trans 'Purchase Request Form'%}</a></li>
    </ul>
  </li>
  {% endif %}

  {% if request.user|has_group:"Admin" %}
  <li class="nav-item dropdown">
    <a class="dropdown-toggle" href="javascript:void(0);"><span class="icon-holder"><i class="c-blue-500 ti-alarm-clock"></i> </span><span class="title">{% trans "Work Days Management" %}</span>
      <span class="arrow"><i class="ti-angle-right"></i></span></a>
    <ul class="dropdown-menu">
      <li><a href="javascript:void(0);">
          <span>{% trans 'Employee Leave setup'%}</span>
          <span class="arrow"><i class="ti-angle-right"></i></span>
        </a>
        <ul class="dropdown-menu" style="display: none;">
          <li><a href="{% url 'leave:leave-balance' %}">{% trans "Employees Leave Balance" %}</a></li>
          <li><a href="{% url 'leave:list-leave-master' %}">{% trans "Leaves Type Setup" %}</a></li>
        </ul>
      </li>
    </ul>
    <ul class="dropdown-menu">

      <li><a href="javascript:void(0);">
          <span>{% trans 'Working Policies'%}</span>
          <span class="arrow"><i class="ti-angle-right"></i></span>
        </a>
        <ul class="dropdown-menu" style="display: none;">
          <li><a href="{% url 'company:working-hrs-policy-list' %}">{% trans "Working Hours Policy" %}</a></li>
          <li><a href="{% url 'company:working-hrs-deductions-list' %}">{% trans "Deductions Policy" %}</a></li>
          <li><a href="{% url 'company:list-years' %}">{% trans "Yearly Holidays" %}</a></li>
        </ul>
      </li>
    </ul>
  </li>
  <li class="nav-item dropdown">
    <a class="dropdown-toggle" href="javascript:void(0);"><span class="icon-holder"><i class="c-blue-500 ti-alarm-clock"></i>
      </span><span class="title">{% trans "Attendance Management" %}</span> <span class="arrow"><i class="ti-angle-right"></i></span>
    </a>
    <ul class="dropdown-menu">
      <!-- <li><a class="sidebar-link" href="{% url 'attendance:list-machine-log' %}">{% trans 'Connect To Machine'%}</a></li> -->
      <!-- <li><a class="sidebar-link" href="{% url 'attendance:list-attendance-deductions' %}">{% trans 'List Absence'%}</a></li> -->
      <li><a class="sidebar-link" href="{% url 'attendance:upload-attendance' %}">{% trans 'Upload Excel File' %}</a></li>
      <li><a class="sidebar-link" href="{% url 'attendance:attendance-export' %}">{% trans 'Export  File' %}</a></li>
      <li><a class="sidebar-link" href="{% url 'attendance:user-list-attendance' %}">{% trans 'Working From Home' %}</a></li>
    </ul>
  </li>
  {% endif %}
  {% if request.user|has_group:"Admin" or request.user|has_group:"Employee" %}
  <li class="nav-item dropdown">
    <a class="dropdown-toggle" href="javascript:void(0);"><span class="icon-holder"><i class="c-blue-500 ti-alarm-clock"></i> </span><span class="title">{% trans "Task Management" %}</span> <span class="arrow"><i
          class="ti-angle-right"></i></span></a>
    <ul class="dropdown-menu">
      <li><a class="sidebar-link" href="{% url 'task_management:task-list' %}">{% trans 'User Tasks' %}</a></li>
    </ul>
  </li>
  {% endif %}

  <li class="nav-item dropdown">
    <a class="dropdown-toggle" href="javascript:void(0);"><span class="icon-holder"><i class="c-blue-500 ti-alarm-clock"></i> </span><span class="title">{% trans "Performance Management" %}</span> <span class="arrow"><i
          class="ti-angle-right"></i></span></a>
    <ul class="dropdown-menu">
      <li><a class="sidebar-link" href="{% url 'performance:performance-list' %}">{% trans 'Performances' %}</a></li>
    </ul>
  </li>


  <li class="nav-item dropdown">
    <a class="dropdown-toggle" href="javascript:void(0);"><span class="icon-holder"><i class="c-blue-500 ti-alarm-clock"></i> </span><span class="title">{% trans "Employee Performance" %}</span> <span class="arrow"><i
          class="ti-angle-right"></i></span></a>
    <ul class="dropdown-menu">
      <li><a class="sidebar-link" href="{% url 'performance:employees' %}">{% trans 'Employees' %}</a></li>
    </ul>
  </li>

</div>

MashreqPayroll/templates/side_nav_user.html
{% load i18n %}
{% load l10n %}
{% load staticfiles %}

<div class="sidebar-inner">
  <div class="sidebar-logo">
    <div class="peers ai-c fxw-nw">
      <div class="peer peer-greed">
        <a class="sidebar-link td-n" href="{% url 'home:homepage' %}">
          <div class="peers ai-c fxw-nw">
            <div class="peer">
              <div class="logo"><img src="{% static 'assets/static/images/logo.png' %}" alt=""></div>
            </div>
            <div class="peer peer-greed">
              <h5 class="lh-1 mB-0 logo-text">PeopleM8</h5>
            </div>
          </div>
        </a>
      </div>
      <div class="peer">
        <div class="mobile-toggle sidebar-toggle"><a href="#" class="td-n"><i class="ti-arrow-circle-left"></i></a></div>
      </div>
    </div>
  </div>
  <ul class="sidebar-menu scrollable pos-r">
    <li class="nav-item dropdown">
      <a class="dropdown-toggle" href="javascript:void(0);"><span class="icon-holder">
        <i class="c-pink-500 ti-agenda"></i>
      </span><span class="title">{% trans "Services" %}</span> <span class="arrow"><i class="ti-angle-right"></i></span></a>
      <ul class="dropdown-menu">
        <li><a class="sidebar-link" href="{% url 'service:services_list' %}">{% trans 'Bussiness Travel Form'%}</a></li>
        <li><a class="sidebar-link" href="{% url 'service:purchase-request-list' %}">{% trans 'Purchase Request Form'%}</a></li>
      </ul>
    </li>
    <li class="nav-item dropdown">
      <a class="dropdown-toggle" href="javascript:void(0);"><span class="icon-holder"><i class="c-blue-500 ti-alarm-clock"></i> </span><span class="title">{% trans "Attendance" %}</span> <span class="arrow"><i class="ti-angle-right"></i></span></a>
      <ul class="dropdown-menu">
        <li><a class="sidebar-link" href="{% url 'attendance:user-list-attendance' %}">{% trans 'Manual Attendance'%}</a></li>
        <li><a class="sidebar-link" href="{% url 'leave:list_leave' %}">{% trans 'Leave Form'%}</a></li>
      </ul>
    </li>
  </ul>
</div>